import { Footer, Header } from "@/components";
import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
  weight: ["400", "700"], // 日本語Webフォントでたくさんのウェイトを使用すると非常に重くなるため、ウェイトは2つだけに制限。
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${notoSansJP.variable} flex min-h-dvh flex-col text-slate-900 antialiased`}
      >
        <Header />
        <main className="flex grow flex-col items-center">
          <div className="max-w-md">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
