name: PR Preview Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove PR preview
        run: |
          if [ -d "pr-${{ github.event.number }}" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            rm -rf "pr-${{ github.event.number }}"
            git add .
            git commit -m "Remove preview for PR #${{ github.event.number }}" || exit 0
            git push
            echo "Preview for PR #${{ github.event.number }} has been removed"
          else
            echo "No preview found for PR #${{ github.event.number }}"
          fi